health_check_port: 8085
server_config:
  transaction_stream_config:
    indexer_grpc_data_service_address: "https://grpc.mainnet.aptoslabs.com:443"
    auth_token: "aptoslabs_L7TnCkvEToY_DHz29qyTc9VoKSBfMaJCeLCHMhWAFEeeD"
    request_name_header: "events-processor"
    starting_version: 0
    request_ending_version: 4
  postgres_config:
    connection_string: postgresql://postgres:root@localhost:5432/indexer